# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afa4d390722b9b39c14ffdcd3a9ee5323f7880dacbf22d95de20abedf2b4d2eefe402a6d9c58d5526ebd4a4776f2dbd54c5aae3b43b1c2b098afb0bee303ffe8

test:
  secret_key_base: 5754cd1b40d15723c42f4d2c5459035fe127c961087e800807feb9973d61bcc529a871c2037f2a7f9e188aa15dd62bc73012d7cbf9bc364f5a834ea50176989e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
